project:
  type: book
  output-dir: docs

execute:
  freeze: auto

lang: pt

book:
  title: "Bases da Engenharia de Software 4"
  subtitle: "Banco de Dados"
  site-url: "https://BragaD.github.io/UnDF-BancodeDados-202601"
  repo-url: "https://github.com/BragaD/UnDF-BancodeDados-202601"
  repo-actions: [issue]
  date: today
  date-format: "DD/MM/YYYY"
  chapters:
    - text: "Início"
      href: index.qmd
    - part: "Fundamentos"
      chapters:
        - href: 01-introducao.qmd
          text: "1. Introdução a Bancos de Dados"

page-navigation: true

page-footer:
  border: true
  left: "UnDF - Engenharia de Software - Banco de Dados - 2026.1"
  right:
    - icon: github
      href: "https://github.com/BragaD/UnDF-BancodeDados-202601"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4
    toc-title: "Nesta página"
    link-external-icon: true
    link-external-newwindow: true
    code-copy: true
    code-overflow: wrap

bibliography: references.bib

editor: source
code-annotations: hover

author:
  - name: "Douglas Braga"
    email: "douglas.braga@undf.edu.br"
