# Aplicações de Banco de Dados

## Informações Empresariais

- **Vendas**: clientes, produtos, compras
- **Contabilidade**: pagamentos, recebimentos, ativos
- **Recursos Humanos**: informações sobre funcionários, salários, impostos sobre a folha de pagamento
- **Manufatura**: gestão de produção, estoque, pedidos e cadeia de suprimentos

## Setor Bancário e Financeiro

- Informações de clientes, contas, empréstimos e transações bancárias
- Transações com cartão de crédito
- Finanças: compra e venda de instrumentos financeiros (ações, títulos); dados de mercado em tempo real

## Universidades

- Matrículas, notas

## Companhias Aéreas

- Reservas, horários

## Telecomunicações

- Registros de chamadas, SMS e uso de dados
- Geração de faturas mensais
- Saldos de cartões pré-pagos

## Serviços Web

- **Varejistas online**: rastreamento de pedidos, recomendações personalizadas
- Publicidade online

## Outras Aplicações

- **Bancos de documentos**
- **Sistemas de navegação**: manutenção de localizações de pontos de interesse e rotas de estradas, sistemas de trem, ônibus etc.
